# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-08 14:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('short_text', models.CharField(blank=True, max_length=300, verbose_name='Краткое описание')),
                ('text', models.TextField(blank=True, verbose_name='Полное описание')),
                ('img', models.ImageField(blank=True, upload_to='event/', verbose_name='Изображение')),
                ('event_date', models.DateTimeField(verbose_name='Дата события')),
                ('published_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
            ],
        ),
        migrations.CreateModel(
            name='Formation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Название клубного формирования')),
                ('short_text', models.CharField(blank=True, max_length=300, verbose_name='Краткое описание')),
                ('text', models.TextField(blank=True, verbose_name='Полное описание')),
                ('leader', models.CharField(max_length=300, verbose_name='Руководитель')),
            ],
        ),
        migrations.CreateModel(
            name='FormationTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('Mon', 'Понедельник'), ('Tue', 'Вторник'), ('Wed', 'Среда'), ('Thu', 'Четверг'), ('Fri', 'Пятница'), ('Sat', 'Суббота'), ('Sun', 'Воскресенье')], max_length=3)),
                ('time', models.TimeField()),
                ('formation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formation_times', to='core.Formation')),
            ],
            options={
                'ordering': ['time', 'day'],
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('short_text', models.CharField(blank=True, max_length=300, verbose_name='Краткое описание')),
                ('text', models.TextField(blank=True, verbose_name='Полное описание')),
                ('published_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, verbose_name='Название фотографии')),
                ('img', models.ImageField(upload_to='photo/', verbose_name='Изображение')),
            ],
        ),
        migrations.CreateModel(
            name='PhotoAlbum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название Альбома')),
                ('img', models.ImageField(upload_to='albums/', verbose_name='Превью Альбома')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Тэг')),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, verbose_name='Название видео')),
                ('url', models.URLField(verbose_name='Ссылка на видео')),
                ('tags', models.ManyToManyField(blank=True, related_name='videos', to='core.Tag')),
            ],
        ),
        migrations.AddField(
            model_name='photo',
            name='album',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='core.PhotoAlbum'),
        ),
        migrations.AddField(
            model_name='photo',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='photos', to='core.Tag'),
        ),
        migrations.AddField(
            model_name='note',
            name='photos',
            field=models.ManyToManyField(blank=True, related_name='notes', to='core.Photo'),
        ),
        migrations.AddField(
            model_name='note',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='notes', to='core.Tag'),
        ),
        migrations.AddField(
            model_name='formation',
            name='photos',
            field=models.ManyToManyField(blank=True, related_name='formations', to='core.Photo'),
        ),
        migrations.AddField(
            model_name='event',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='events', to='core.Tag'),
        ),
    ]
