# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-08 16:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='url',
            field=models.URLField(default=1, verbose_name='Ссылка на видео'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='video',
            name='url_id',
            field=models.URLField(blank=True, null=True, verbose_name='id видео'),
        ),
    ]
