# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-09 12:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='note',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='video',
            name='tags',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
