# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-08 15:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-event_date']},
        ),
        migrations.AlterModelOptions(
            name='note',
            options={'ordering': ['-published_date']},
        ),
        migrations.RemoveField(
            model_name='event',
            name='published_date',
        ),
        migrations.AlterField(
            model_name='photoalbum',
            name='img',
            field=models.ImageField(blank=True, upload_to='albums/', verbose_name='Превью Альбома'),
        ),
    ]
