# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-19 15:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20160519_1440'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='photos', to='core.Tag'),
        ),
        migrations.AddField(
            model_name='video',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='videos', to='core.Tag'),
        ),
        migrations.AlterField(
            model_name='note',
            name='photos',
            field=models.ManyToManyField(related_name='notes', to='core.Photo'),
        ),
    ]
