# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-19 15:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20160519_1501'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='tags',
        ),
        migrations.AlterField(
            model_name='photo',
            name='img',
            field=models.ImageField(upload_to='photo/', verbose_name='Изображение'),
        ),
    ]
