# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-19 15:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20160519_1510'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='photos', to='core.Tag'),
        ),
    ]
