# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-19 17:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20160519_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formation',
            name='title',
            field=models.CharField(blank=True, max_length=200, verbose_name='Название клубного формирования'),
        ),
    ]
