# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-02 21:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20160519_1733'),
    ]

    operations = [
        migrations.AddField(
            model_name='formation',
            name='leader',
            field=models.CharField(default=1, max_length=300, verbose_name='Руководитель'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='formation',
            name='photos',
            field=models.ManyToManyField(blank=True, related_name='formations', to='core.Photo'),
        ),
        migrations.AlterField(
            model_name='formationtime',
            name='formation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Formation'),
        ),
        migrations.AlterField(
            model_name='note',
            name='photos',
            field=models.ManyToManyField(blank=True, related_name='notes', to='core.Photo'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='title',
            field=models.CharField(blank=True, max_length=100, verbose_name='Название фотографии'),
        ),
        migrations.AlterField(
            model_name='photoalbum',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Название Альбома'),
        ),
    ]
